// Generated by dts-bundle v0.2.0

declare module 'typed-react' {
   
    export class NotImplementedError implements Error {
        name: string;
        message: string;
        constructor(methodName: string);
    }
    export class Mixin<P, S> implements React.Mixin<P, S> {
        refs: {
            [x: string]: React.Component<any>;
        };
        props: P;
        state: S;
        getDOMNode(): Element;
        setState(nextState: S, callback?: () => void): void;
        replaceState(nextState: S, callback?: () => void): void;
        forceUpdate(callback?: () => void): void;
        isMounted(): boolean;
        setProps(nextProps: P, callback?: () => void): void;
        replaceProps(nextProps: P, callback?: () => void): void;
    }
    export class Component<P, S> extends Mixin<P, S> implements React.CompositeComponent<P, S> {
        render(): React.ReactElement<any>;
    }
    export function createMixin<P, S>(clazz: new () => Mixin<P, S>): React.Mixin<P, S>;
    export function createClass<P, S>(clazz: new () => Component<P, S>, mixins?: React.Mixin<P, S>[]): React.ComponentClass<P>;
}

